---
title: "manuscript-elements"
format: html
editor: source
---

```{r}
# get a list of files
files <- list.files("figures-tables/")
```

```{r}
# check the files
print(files)
```

```{r}
# load relevant libraries
library(ggplot2)
library(patchwork)
```

```{r}
# set-up a vector of species names
sp_names <- c("Erigeron_canadensis", "Phytolacca_americana", "Solidago_gigantea", "Sporobolus_indicus")
```

```{r}
# function to extract the relevant output
get_output_file <- function(prefix, species, exclude_high_N) {
  paste0(prefix, species, "-exclude_high_N-", exclude_high_N, ".rds")
}
```

## Experiment 1

### Table S1

```{r}
# set-up the relevant prefix
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "summary-tbl-exp1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z, 
                   file = file.path("publication/", paste0("tbl-s1-", sp_names[i], ".csv")))
}
```


### Figure 2

```{r}
# get relevant figure tags
fig_tags <- list(c("a", "b"), c("c", "d"), c("e", "f"), c("g", "h"))

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
}

# extract the legend
p_leg <- cowplot::get_legend(p_list[[1]])

# remove the legends
for (i in seq_along(p_list)) {
  p_list[[i]] <-
    p_list[[i]] + 
    plot_layout(guides = "collect") &
    theme(legend.position = "none")
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)

# check the plot
p1
```

```{r}
# add a legend using patchwork
p1 <- p1 + p_leg + plot_layout(widths = c(7, 1))

# check the plot
p1
```

```{r}
# export the plot
ggsave(filename = "publication/fig-2.png", p1, dpi = 600,
       units = c("cm"), width = 22, height = 14)
```

### Figure 3

```{r}
# get relevant figure tags
fig_tags <- list(c("a", "b"), c("c", "d"), c("e", "f"), c("g", "h"))

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp1-mm2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
  p_list[[i]] <- z & theme(axis.title.x = element_text(size = 8))
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)

# check the plot
p1
```

```{r}
# export the plot
ggsave(filename = "publication/fig-3.png", p1, dpi = 600,
       units = c("cm"), width = 22, height = 14)
```

### Table 1

```{r}
# set-up the relevant prefix
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "lrt-tbl-exp1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z, 
                   file = file.path("publication/", paste0("tbl-1-", sp_names[i], ".csv")))
}
```


### Figure S2

```{r}
# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp1-mm1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y & theme(axis.title.x = element_text(size = 8))
}

# check the plots
p_list[[1]]
```

```{r}
# bind the plots
p1 <- 
  p_list[[1]] + p_list[[2]] + p_list[[3]] + p_list[[4]] +
  plot_annotation(tag_levels = "a")

# check the plots
plot(p1)
```

```{r}
# export the plot
ggsave(filename = "publication/fig-s2.png", p1, dpi = 600,
       units = c("cm"), width = 19, height = 16)
```

### Table S2

```{r}
# set-up the relevant prefix
x <- readRDS(file.path("figures-tables/", "cv-tbl-exp1-exclude_high_N-FALSE.rds"))
readr::write_csv(x = x, 
                 file = file.path("publication/", paste0("tbl-s2.csv")))
```


### Table S3

Anova table for the best model:

```{r}
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "aov-tbl-exp1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z,
                   file = file.path("publication/", paste0("tbl-s3-", sp_names[i], ".csv")))
}
```


### Table S4

```{r}
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "best-mod-tbl-exp1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z,
                   file = file.path("publication/", paste0("tbl-s4-", sp_names[i], ".csv")))
}
```


## Experiment 2

### Table S5

```{r}
# set-up the relevant prefix
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "summary-tbl-exp2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z, 
                   file = file.path("publication/", paste0("tbl-s5-", sp_names[i], ".csv")))
}
```


### Figure 4

```{r}
# get relevant figure tags
fig_tags <- list(c("a", "b"), c("c", "d"), c("e", "f"), c("g", "h"))

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
}

# get the relevant legend
p_leg <- 
  p_list[[1]] + plot_layout(guides = "collect") & 
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "white", colour = "white"),
        legend.box.background = element_rect(fill = "white", colour = "white"))

# extract the legend
p_leg <- cowplot::get_legend(p_leg)

# remove the legends
for (i in seq_along(p_list)) {
  p_list[[i]] <- 
    p_list[[i]] + 
    plot_layout(guides = "collect") &
    theme(legend.position = "none")
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)
p1 <- cowplot::plot_grid(p1, p_leg, ncol = 1, nrow = 2,
                         rel_heights = c(2.5, 0.2))

# check the plot
p1
```

```{r}
# export the plot
ggsave(filename = "publication/fig-4.png", p1, dpi = 600,
       units = c("cm"), width = 20, height = 16)
```

### Figure 5

```{r}
# get relevant figure tags
fig_tags <- list(c("a", "b"), c("c", "d"), c("e", "f"), c("g", "h"))

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp2-mm2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
  p_list[[i]] <- z & theme(axis.title.x = element_text(size = 8))
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)

# check the plot
p1
```

```{r}
# export the plot
ggsave(filename = "publication/fig-5.png", p1, dpi = 600,
       units = c("cm"), width = 22, height = 14)
```


### Table 2

```{r}
# set-up the relevant prefix
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "lrt-tbl-exp2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z, 
                   file = file.path("publication/", paste0("tbl-2-", sp_names[i], ".csv")))
}
```


### Figure S3

```{r}
# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-exp2-mm1-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y & theme(axis.title.x = element_text(size = 8))
}

# check the plots
p_list[[1]]
```

```{r}
# bind the plots
p1 <- 
  p_list[[1]] + p_list[[2]] + p_list[[3]] + p_list[[4]] +
  plot_annotation(tag_levels = "a")

# check the plots
plot(p1)
```


```{r}
# export the plot
ggsave(filename = "publication/fig-s3.png", p1, dpi = 600,
       units = c("cm"), width = 19, height = 16)
```


### Table S6

```{r}
# set-up the relevant prefix
x <- readRDS(file.path("figures-tables/", "cv-tbl-exp2-exclude_high_N-FALSE.rds"))
readr::write_csv(x = x, 
                 file = file.path("publication/", paste0("tbl-s6.csv")))
```


### Table S7

Anova table for experiment 2:

```{r}
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "aov-tbl-exp2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z,
                   file = file.path("publication/", paste0("tbl-s7-", sp_names[i], ".csv")))
}
```

### Table S8

```{r}
tb_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "best-mod-tbl-exp2-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables", x))
  z <- dplyr::bind_cols(dplyr::tibble(Species = sp_names[i]), y)
  readr::write_csv(x = z,
                   file = file.path("publication/", paste0("tbl-s8-", sp_names[i], ".csv")))
}
```


## Individual species responses

### Figure S4

```{r}
# get relevant figure tags
fig_tags <- list(letters[1:4], letters[5:8], 
                 letters[9:12], letters[13:16])

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-ind-response-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
}

# extract the legend
p_leg <- cowplot::get_legend(p_list[[1]])

# remove the legends
for (i in seq_along(p_list)) {
  p_list[[i]] <-
    p_list[[i]] + 
    plot_layout(guides = "collect") &
    theme(legend.position = "none")
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)

# check the plot
p1
```

```{r}
# add a legend using patchwork
p1 <- p1 + p_leg + plot_layout(widths = c(7, 1))

# check the plot
p1
```

```{r}
# export the plot
ggsave(filename = "publication/fig-s4.png", p1, dpi = 600,
       units = c("cm"), width = 22, height = 26)
```

## Simulation

### Figure S5

```{r}
# get relevant figure tags
fig_tags <- list(c("a", "b"), c("c", "d"), c("e", "f"), c("g", "h"))

# load the relevant figures for each species
p_list <- list()
for (i in seq_along(sp_names)) {
  x <- get_output_file(prefix = "fig-simulation-", species = sp_names[i], exclude_high_N = "FALSE")
  y <- readRDS(file.path("figures-tables/", x))
  p_list[[i]] <- y + plot_annotation(tag_levels = list(fig_tags[[i]]))
}

# get the relevant legend
p_leg <- 
  p_list[[1]] + plot_layout(guides = "collect") & 
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "white", colour = "white"),
        legend.box.background = element_rect(fill = "white", colour = "white"))

# extract the legend
p_leg <- cowplot::get_legend(p_leg)

# remove the legends
for (i in seq_along(p_list)) {
  p_list[[i]] <- 
    p_list[[i]] + 
    plot_layout(guides = "collect") &
    theme(legend.position = "none")
}
```

```{r}
# bind using cowplot
p1 <- cowplot::plot_grid(plotlist = p_list)
p1 <- cowplot::plot_grid(p1, p_leg, ncol = 1, nrow = 2,
                         rel_heights = c(2.5, 0.2))

# check the plot
p1
```


```{r}
# export the plot
ggsave(filename = "publication/fig-s5.png", p1, dpi = 600,
       units = c("cm"), width = 20, height = 16)
```



