---
title: "Additional analysis"
format: html
editor: visual
---

Based on the analysis, we wanted to explore the functional form of the relationship between nitrogen and biomass with and without microbes for natives and invasives:

```{r}
# load the raw data
dat_raw <- readr::read_csv2(here::here("data-raw/all-raw-data-response-phase.csv"),
                            guess_max = 1000)
```

```{r}
# set the species
i_species_sel <- "Phytolacca_americana"

# clean the data
dat_ex1 <- clean_exp1(data = dat_raw,
                      i_species = i_species_sel,
                      exclude_high_N = FALSE) 

# check the data
head(dat_ex1)
```

```{r}
# without microbes

# native species
dat_ex1_noM_Nat <-
  dat_ex1 |>
  dplyr::filter(M == 0, P == 0)

# invasive species
dat_ex1_noM_Inv <-
  dat_ex1 |>
  dplyr::filter(M == 0, P == 1)
```

```{r}
plot(dat_ex1_noM_Nat$N, dat_ex1_noM_Nat$B) 
```



```{r}
# with microbes

# native species
dat_ex1_M_Nat <-
  dat_ex1 |>
  dplyr::filter(M == 1, P == 0)

# invasive species
dat_ex1_M_Inv <-
  dat_ex1 |>
  dplyr::filter(M == 1, P == 1)
```




